// ------------------------------------------------------------------------------
//  <autogenerated>
//      This code was generated by a tool.
//      Mono Runtime Version: 4.0.30319.1
// 
//      Changes to this file may cause incorrect behavior and will be lost if 
//      the code is regenerated.
//  </autogenerated>
// ------------------------------------------------------------------------------
using System;
using Tenkafubu.Sqlite;


namespace Tenkafubu.Migrate
{
	public class AutoTable
	{
		DB database;
		DBMigrate migrate;
		public AutoTable (DB database)
		{
			this.database = database;
			this.migrate = new DBMigrate(database);
			migrate.hashMismatchAction = HashMismatchAction.RecreateTable;
		}

		public void AutoCreate<T>() where T : class{
			var ope = database.GetOperation<T>();
			var sql = ope.Converter.ToCreateTable();
			migrate.Migrate(ope.Converter.TableName,sql);
		}

	}
}

