// ------------------------------------------------------------------------------
//  <autogenerated>
//      This code was generated by a tool.
//      Mono Runtime Version: 4.0.30319.1
// 
//      Changes to this file may cause incorrect behavior and will be lost if 
//      the code is regenerated.
//  </autogenerated>
// ------------------------------------------------------------------------------
using System;

using System.Collections.Generic;
using System.Text.RegularExpressions;

using Tenkafubu.Concurrent.Factory;

namespace Tenkafubu.Http.Dummy
{
	public class DummyHttpClient : AbstractHttpClient
	{

		List<Tuple2<Regex,string>> matchers = new List<Tuple2<Regex,string>>();

		public DummyHttpClient ()
		{
		}

		public void Register(string pathRegex,string response){
			matchers.Add(Tuples.Tuple(new Regex(pathRegex),response));
		}

		public override Tenkafubu.Concurrent.Future<Response> Send (HttpMethod method, string path, byte[] body)
		{
			foreach(var m in matchers){
				if(m.V1.IsMatch(path)){
					var r = new Response();
					r.status = 200;
					r.bytes = System.Text.Encoding.UTF8.GetBytes(m.V2);
					return FutureFactory.Success(r);
				}
			}
			return FutureFactory.Error<Response>(new Exception("Matcher not found for path:" + path));
		}

	}
}

