// ------------------------------------------------------------------------------
//  <autogenerated>
//      This code was generated by a tool.
//      Mono Runtime Version: 4.0.30319.1
// 
//      Changes to this file may cause incorrect behavior and will be lost if 
//      the code is regenerated.
//  </autogenerated>
// ------------------------------------------------------------------------------
using System;
using System.Collections.Generic;
using System.Security.Cryptography;
using System.Text;

namespace Tenkafubu.Util
{
	public static class HashUtil
	{

		public static string ToBase64(byte[] data){
			return Convert.ToBase64String(data);
		}

		public static string ToMD5(byte[] data){
			var md5 = MD5.Create();
			var hashed = md5.ComputeHash(data);
			return ToHex (hashed);
		}
		public static string ToMD5(string v){
			return ToBase64(Encoding.UTF8.GetBytes(v));

		}

		public static string ToHMacSHA1(string v,string key){
			var hmac = HMACSHA1.Create();
			hmac.Key = Encoding.UTF8.GetBytes(key);
			var d = Encoding.UTF8.GetBytes(v);
			var hashed = hmac.ComputeHash(d);
			return ToBase64(hashed);
		}

		public static string ToHex(byte[] data){
			var b = new StringBuilder(data.Length * 2);
			for(int i = 0;i < data.Length;i++){
				if(data[i] < 16) b.Append("0");
				b.Append(Convert.ToString(data[i],16));
			}
			return b.ToString();
		}

	}
}

